name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code


      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Run tests
        run: npm test  # Run tests

      - name: Build the application
        run: npm run build  # Build the application

  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    needs: build  # Ensure this job runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Deploy to Server
        env:
          DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}  # Use a secret for deployment key
        run: |
          echo "Deploying application..."
          # Add your deployment commands here
          # For example, using SSH to deploy to a server
          ssh -i $DEPLOYMENT_KEY user@your-server "cd /path/to/app && git pull && npm install && npm run start"
